services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: smsgateway_app

    restart: unless-stopped

    env_file:
      - /opt/smsgateway/secrets/smsgateway.env

    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "9088:8080"

    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"

      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

      # Désactive l'affichage de toutes les requêtes SQL dans la console.
      SPRING_JPA_SHOW_SQL: "false"

      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"

    networks:
      - smsgateway-net

networks:
  smsgateway-net:
    name: smsgateway-net
    driver: bridge