spring.application.name=smsgateway

server.port=8080
#spring.datasource.url=jdbc:postgresql://localhost:5432/smsgatewaydb
#spring.datasource.username=postgres
#spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration pour servir des fichiers statiques
#logging.level.org.springframework=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.mail=DEBUG
#logging.level.org.springframework.mail.javamail=DEBUG

# Parametres de connexion au serveur SMTP
app.frontend.reset-url.client=http://localhost:3001/reset-password
app.frontend.reset-url.manager=http://localhost:3001/api/V1/manager/password/reset

spring.mail.host=solutech-one.com
spring.mail.port=465
spring.mail.username=noreply@solutech-one.com
spring.mail.password=5qUlANOYx7P!
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.ssl.enable=true

# ==========================================================
# CONFIGURATION CORS
# Valeurs chargées depuis les variables d'environnement.
# Les valeurs après ":" sont utilisées par défaut.
# ==========================================================

app.security.cors.allowed-origin-patterns=${APP_SECURITY_CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:3001,https://client.i-onsms.es,https://backoffice.i-onsms.es}

app.security.cors.allowed-methods=${APP_SECURITY_CORS_ALLOWED_METHODS:*}

app.security.cors.allowed-headers=${APP_SECURITY_CORS_ALLOWED_HEADERS:*}

app.security.cors.exposed-headers=${APP_SECURITY_CORS_EXPOSED_HEADERS:Authorization,Content-Disposition}

app.security.cors.allow-credentials=${APP_SECURITY_CORS_ALLOW_CREDENTIALS:true}

app.security.cors.max-age=${APP_SECURITY_CORS_MAX_AGE:3600}





